spring.application.name=usecase

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/travel
spring.datasource.username=root
spring.datasource.password=arulraj#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
